# If `True`, then selectively enable data augmentation.
# If `False`, then disable the entire data augmentation.
AUG_ENABLED: True

# 1) Resize
RESIZE:
  ENABLED: True
  # Size of the smallest side of the image during training
  MIN_SIZE_TRAIN: ???
  # Sample size of smallest side by choice or random selection from range give by
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  # Maximum size of the side of the image during training
  MAX_SIZE_TRAIN: ???
  # Size of the smallest side of the image during testing. Set to zero to disable resize in testing.
  MIN_SIZE_TEST: ???
  # Maximum size of the side of the image during testing
  MAX_SIZE_TEST: ???

# 2) Crop
CROP:
  # `True` if cropping is used for data augmentation during training
  ENABLED: False
  # Cropping type:
  # - "relative" crop (H * CROP.SIZE[0], W * CROP.SIZE[1]) part of an input of size (H, W)
  # - "relative_range" uniformly sample relative crop size from between [CROP.SIZE[0], [CROP.SIZE[1]].
  #   and  [1, 1] and use it as in "relative" scenario.
  # - "absolute" crop part of an input with absolute size: (CROP.SIZE[0], CROP.SIZE[1]).
  # - "absolute_range", for an input of size (H, W), uniformly sample H_crop in
  #   [CROP.SIZE[0], min(H, CROP.SIZE[1])] and W_crop in [CROP.SIZE[0], min(W, CROP.SIZE[1])]
  TYPE: "relative_range"
  # Size of crop in range (0, 1] if CROP.TYPE is "relative" or "relative_range" and in number of
  # pixels if CROP.TYPE is "absolute"
  SIZE: [0.9, 0.9]

# 3) Flip.
RANDOM_FLIP:
  # NOTE: Unlike d2, RandomFlip is configurable
  ENABLED:  True
  HORIZONTAL: True
  VERTICAL: False

# 4) Color jittering
COLOR_JITTER:
  ENABLED:  True
  BRIGHTNESS: [0.2, 0.2]
  SATURATION: [0.2, 0.2]
  CONTRAST: [0.2, 0.2]
